repost_script/urls.py
from django.contrib import admin
from django.urls import path, include

from repost_script import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('script.urls')),
    path('account/', include('usermanage.urls')),
    path('', views.IndexView.as_view())
]

script/urls.py
from django.urls import path

from . import views

app_name = 'script'
urlpatterns = [
    path('templates/create', views.CreateTemplateView.as_view(), name='create_template'),
    path('templates/<int:template_id>', views.UpdateTemplateView.as_view(), name='template_detail'),
    path('templates/<int:template_id>/copy', views.CopyTemplateView.as_view(), name='copy_template'),
    path('templates/updateOrderApi', views.UpdateTemplateOrderApi.as_view(),
         name='update_template_order_api'),
    path('templates/getByIdApi', views.GetTemplateByIdApi.as_view(), name='get_template_by_id_api'),
    path('templates/deleteApi', views.DeleteTemplateApi.as_view(), name='delete_template_api'),
    path('templates/', views.ListTemplatesView.as_view(), name='list_templates'),
    path('post/<int:post_id>', views.UpdatePostView.as_view(), name='update_post'),
    path('post/updateApi', views.UpdatePostApi.as_view(), name='update_post_api'),
    path('post/add', views.AddPostView.as_view(), name='add_post'),
    path('post/addApi', views.AddPostApi.as_view(), name='add_post_api'),
    path('settings', views.Settings.as_view(), name='settings'),
    path('vk_login', views.VKRedirectURI.as_view(), name='vk_redirect_uri'),
    path('tg_api', views.TGApi.as_view(), name='tg_api'),
    path('save_api', views.SaveApi.as_view(), name='save_api'),
    path('', views.IndexView.as_view(), name='index')
]

usermanage/urls.py
from django.urls import path
from django.contrib.auth.urls import views as auth_views
from django.views.generic import RedirectView

from usermanage import views

app_name = 'usermanage'
urlpatterns = [
    path('reg', views.Reg.as_view(), name='reg'),
    path('login', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('change_password', auth_views.PasswordChangeView.as_view(), name='change_password'),
    path('change_password/done', auth_views.PasswordChangeDoneView.as_view(), name='change_password_done'),
    path('', RedirectView.as_view(pattern_name='script:add_post'))
]

usermanage/models.py
from django.db import models

# Create your models here.

usermanage/views.py
import hashlib

import requests
from django.conf import settings
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.http.response import JsonResponse
from django.shortcuts import redirect, render
# Create your views here.
from django.views import View
from django.views.generic import TemplateView

from script.models import Info, NotifyType
from tg_api import TgRequest


class Reg(View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect('script:add_post')
        form = UserCreationForm()
        return render(request, 'usermanage/reg.html', {'form': form})

    def post(self, request):
        if request.user.is_authenticated:
            return redirect('script:add_post')
        form = UserCreationForm(request.POST)
        if not form.is_valid():
            return render(request, 'usermanage/reg.html', {'form': form})
        user = User.objects.create_user(username=form.cleaned_data['username'], password=form.cleaned_data['password1'])
        login(request, user)
        return redirect('script:settings')

usermanage/templates/usermanage/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Reposter | {% block title %}{% endblock title %}</title>
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0 maximum-scale=1.0">
    {% include 'icons/html_code.html' %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'usermanage/base.css' %}">
    {% block head %}

    {% endblock head %}
</head>
<body>
<div class="content">
    <div class="header-wrapper">
        {% block header %}
            <h1 class="header">
                {% block header_text %}
                {% endblock header_text %}
            </h1>
        {% endblock header %}
    </div>
    {% block content %}

    {% endblock content %}
</div>
</body>
</html>

usermanage/templates/usermanage/reg.html
{% extends 'usermanage/base.html' %}

{% block title %}Регистрация{% endblock %}

{% block header_text %}Регистрация{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="fieldWrapper">
                {{ field.errors }}
                {{ field.label_tag }}
                {{ field }}
            </div>
        {% endfor %}
        <div class="bottom">
            <a href="{% url 'usermanage:login' %}" class="text">Уже есть аккаунт?<br/>Войти</a>
            <button>Зарегистрироваться</button>
        </div>
    </form>
{% endblock %}