repost_script/urls.py
from django.contrib import admin
from django.urls import path, include

from repost_script import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('script.urls')),
    path('account/', include('usermanage.urls')),
    path('', views.IndexView.as_view())
]

script/urls.py
from django.urls import path

from . import views

app_name = 'script'
urlpatterns = [
    path('templates/create', views.CreateTemplateView.as_view(), name='create_template'),
    path('templates/<int:template_id>', views.UpdateTemplateView.as_view(), name='template_detail'),
    path('templates/<int:template_id>/copy', views.CopyTemplateView.as_view(), name='copy_template'),
    path('templates/updateOrderApi', views.UpdateTemplateOrderApi.as_view(),
         name='update_template_order_api'),
    path('templates/getByIdApi', views.GetTemplateByIdApi.as_view(), name='get_template_by_id_api'),
    path('templates/deleteApi', views.DeleteTemplateApi.as_view(), name='delete_template_api'),
    path('templates/', views.ListTemplatesView.as_view(), name='list_templates'),
    path('post/<int:post_id>', views.UpdatePostView.as_view(), name='update_post'),
    path('post/updateApi', views.UpdatePostApi.as_view(), name='update_post_api'),
    path('post/add', views.AddPostView.as_view(), name='add_post'),
    path('post/addApi', views.AddPostApi.as_view(), name='add_post_api'),
    path('settings', views.Settings.as_view(), name='settings'),
    path('vk_login', views.VKRedirectURI.as_view(), name='vk_redirect_uri'),
    path('tg_api', views.TGApi.as_view(), name='tg_api'),
    path('save_api', views.SaveApi.as_view(), name='save_api'),
    path('', views.IndexView.as_view(), name='index')
]

usermanage/urls.py
from django.urls import path
from django.contrib.auth.urls import views as auth_views
from django.views.generic import RedirectView

from usermanage import views

app_name = 'usermanage'
urlpatterns = [
    path('reg', views.Reg.as_view(), name='reg'),
    path('login', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('change_password', auth_views.PasswordChangeView.as_view(), name='change_password'),
    path('change_password/done', auth_views.PasswordChangeDoneView.as_view(), name='change_password_done'),
    path('', RedirectView.as_view(pattern_name='script:add_post'))
]

script/models.py
from django.contrib.auth import get_user_model
from django.db import models

# Create your models here.
from django.utils import timezone


class Post(models.Model):
    link = models.URLField()
    public = models.CharField(max_length=40)
    text = models.TextField()
    image = models.URLField()
    datetime = models.DateTimeField()
    created = models.DateTimeField()
    new_post_id = models.CharField(max_length=40, blank=True)
    type = models.ForeignKey('Type', on_delete=models.SET_NULL, null=True)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, db_index=True)
    attempts = models.PositiveSmallIntegerField(default=0)

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.pk:
            self.created = timezone.now()
        super().save(force_insert, force_update, using, update_fields)

    def __str__(self):
        return self.link


class Template(models.Model):
    name = models.CharField(max_length=80, verbose_name='Имя')
    photos = models.TextField(verbose_name='Ссылки на изображения', blank=True)
    posts = models.TextField(verbose_name='Ссылки на посты', blank=True)
    publics = models.TextField(verbose_name='Паблики', blank=True)
    texts = models.TextField(verbose_name='Тексты', blank=True)
    times = models.TextField(verbose_name='Время постов', blank=True)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, db_index=True)
    order_id = models.PositiveIntegerField()
    created = models.DateTimeField()
    active = models.BooleanField(default=True)

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.pk:
            self.created = timezone.now()
        if not self.order_id:
            last = self.__class__.objects.all().last()
            self.order_id = self.pk or (last and last.pk + 1) or 1
        super().save(force_insert, force_update, using, update_fields)

    def __str__(self):
        return self.name


class Info(models.Model):
    vk_id = models.BigIntegerField(primary_key=True)
    access_token = models.CharField(max_length=200)
    tg_id = models.BigIntegerField(blank=True, null=True)
    notify_type = models.ForeignKey('NotifyType', on_delete=models.CASCADE, default=1)
    profile_dir = models.CharField(max_length=20, blank=True)
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE, db_index=True)

    def __str__(self):
        return str(self.user)


class Type(models.Model):
    text = models.CharField(max_length=15)

    def __str__(self):
        return self.text


class NotifyType(models.Model):
    text = models.CharField(max_length=15)

    def __str__(self):
        return self.text

script/forms.py
from django.forms import ModelForm

from script.models import Template


class TemplateForm(ModelForm):
    class Meta:
        model = Template
        fields = ('name', 'photos', 'posts', 'publics', 'texts', 'times')

script/views.py
import hashlib
import re
from datetime import timedelta, timezone as datetime_timezone

import requests
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http.response import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone as django_timezone
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.csrf import ensure_csrf_cookie
from django.views.generic import ListView
from django.views.generic.base import RedirectView, TemplateView

from article import is_article_link
from script.datetime_parser import Parser, DatetimeParserException
from script.forms import TemplateForm
from script.models import Post, Template, Type, Info, NotifyType
from tg_api import TgRequest
from .mixins import InfoRequiredMixin

vk_redirect_uri = 'http://' + settings.DOMAIN + '/app/vk_login'
settings_url = 'http://' + settings.DOMAIN + '/app/settings'


def get_tg_hash(user):
    try:
        info_obj = Info.objects.get(user=user)
    except Info.DoesNotExist:
        return None
    vk_id = info_obj.vk_id
    access_token = info_obj.access_token
    if not (vk_id and access_token):
        return None
    hash_str = (str(vk_id) + settings.TG_HASH_SALT + access_token[:round(len(access_token) / 2)]).encode('ascii')
    return hashlib.md5(hash_str).hexdigest()


@method_decorator(ensure_csrf_cookie, name='dispatch')
class AddPostView(LoginRequiredMixin, InfoRequiredMixin, View):
    def get(self, request):
        templates = Template.objects\
            .filter(user=request.user, active=True)\
            .order_by('order_id')
        new_templates = []
        for template in templates:
            new_template = {
                'id': template.id,
                'name': template.name
            }
            new_templates.append(new_template)
        return render(request, 'script/add_post.html', {'templates': new_templates})


@method_decorator(ensure_csrf_cookie, name='dispatch')
class ListTemplatesView(LoginRequiredMixin, ListView):
    model = Template
    allow_empty = True
    template_name = 'script/template_list.html'

    def get_queryset(self):
        return Template.objects\
            .filter(user=self.request.user, active=True)\
            .order_by('order_id')


class CreateTemplateView(LoginRequiredMixin, View):
    def get(self, request):
        form = TemplateForm()
        return render(request, 'script/template.html', {'form': form})

    def post(self, request):
        template = Template(user=request.user, active=True)
        form = TemplateForm(request.POST, instance=template)
        if not form.is_valid():
            return render(request, 'script/template.html', {'form': form})
        form.save()
        return redirect('script:list_templates')


@method_decorator(ensure_csrf_cookie, name='dispatch')
class UpdateTemplateView(LoginRequiredMixin, View):
    def get(self, request, template_id):
        template = get_object_or_404(Template, pk=template_id, user=request.user, active=True)
        data = {
            'name': template.name,
            'photos': template.photos,
            'publics': template.publics,
            'posts': template.posts,
            'texts': template.texts,
            'times': template.times,
        }
        form = TemplateForm(data)
        return render(request, 'script/template.html', {'form': form, 'template_id': template_id})

    def post(self, request, template_id):
        template = Template.objects.get(user=request.user, pk=template_id, active=True)
        form = TemplateForm(request.POST, instance=template)
        if form.is_valid():
            form.save()
        return render(request, 'script/template.html', {'form': form, 'template_id': template_id})


class UpdateTemplateOrderApi(LoginRequiredMixin, View):
    def post(self, request):
        post = request.POST
        for template_id in post:
            template_order = post[template_id]
            Template.objects.filter(pk=template_id).update(order_id=template_order)
        return JsonResponse({'ok': 'ok'})


class CopyTemplateView(LoginRequiredMixin, View):
    def get(self, request, template_id):
        template = get_object_or_404(Template, pk=template_id, user=request.user, active=True)
        Template.objects.create(name='[Копия] ' + template.name,
                                photos=template.photos,
                                posts=template.posts,
                                publics=template.publics,
                                texts=template.texts,
                                times=template.times,
                                user=request.user)
        return redirect('script:list_templates')


class AddPostApi(LoginRequiredMixin, InfoRequiredMixin, View):
    def post(self, request):
        data = request.POST
        links = data.get('links')
        publics = data.get('publics')
        texts = data.get('texts')
        images = data.get('imgs')
        post_datetimes = data.get('datetimes')
        if not (links and publics and texts and images and post_datetimes):
            return JsonResponse({'error': 'Переданы не все нужные параметры'},
                                json_dumps_params={'ensure_ascii': False})
        links = links.splitlines()
        publics = publics.splitlines()
        if '\r\n' in texts:
            texts = texts.split('\r\n_end_\r\n')
        else:
            texts = texts.split("\n_end_\n")
        images = images.splitlines()
        post_datetimes = post_datetimes.splitlines()
        new_texts = []
        for text in texts:
            text = text.strip()
            new_texts.append(text)
        texts = new_texts
        if texts[-1].endswith("\r\n_end_"):
            texts[-1] = texts[-1][0: texts[-1].rfind("\r\n_end_")]
        elif texts[-1].endswith("\n_end_"):
            texts[-1] = texts[-1][0: texts[-1].rfind("\n_end_")]
        i = 0
        datetime_parser = Parser(datetime_timezone(timedelta(hours=3)))
        for post_datetime in post_datetimes:
            try:
                post_datetimes[i] = datetime_parser(post_datetime)
            except DatetimeParserException as e:
                return JsonResponse({'error': f'Неверный формат даты или времени поста №{i + 1}<br>"' + str(e) + '"<br>'
                                              'Нужен "ДД.ММ.ГГГГ ЧЧ:ММ"<br>'
                                              'Или "$<i>число</i> ЧЧ:ММ"<br>'
                                              'Где <i>число</i>: любое число сдвига даты<br>'
                                              'Например: <i>$4 12:25</i><br>'
                                              '(<i>Сегодня</i> = <i>0</i> )<br>'
                                              'На всякий случай ни один пост не был добавлен'},
                                    json_dumps_params={'ensure_ascii': False})
            i += 1
        i = 0
        regex = re.compile('((wall-|wall)\d+_\d+)|(z=article_edit-?\d+_\d+)|(vk.com/@.+)$')
        for link in links:
            match = regex.search(link)
            if not match:
                return JsonResponse({'error': 'Неверная ссылка в посте №{number}<br>'.format(number=i + 1) +
                                              'На всякий случай ни один пост не был добавлен'},
                                    json_dumps_params={'ensure_ascii': False})
            if not is_article_link(link):
                link = 'https://vk.com/' + match.group(0)
                links[i] = link
            i += 1
        i = 0
        for image in images:
            if not ('.png' in image or '.jpg' in image or '.gif' in image or '.webp' in image):
                return JsonResponse({'error': 'Неверная ссылка на картинку в посте №{number}<br>'.format(number=i + 1) +
                                              'На всякий случай ни один пост не был добавлен'},
                                    json_dumps_params={'ensure_ascii': False})
            i += 1
        i = 0
        posts_type = Type.objects.get(pk=1)
        posts = []
        for link in links:
            public = publics[i]
            text = texts[i]
            image = images[i]
            post_datetime = post_datetimes[i]
            post = Post(link=link, public=public, text=text, image=image, datetime=post_datetime,
                        user=request.user, type=posts_type, created=django_timezone.now())
            posts.append(post)
            i += 1
        Post.objects.bulk_create(posts)
        return JsonResponse({'ok': i}, json_dumps_params={'ensure_ascii': False})


class GetTemplateByIdApi(LoginRequiredMixin, View):
    def post(self, request):
        template_id = request.POST.get('id')
        if template_id is None:
            return JsonResponse({'error': 'Не передан id'}, json_dumps_params={'ensure_ascii': False})
        try:
            template = Template.objects.get(user=request.user, pk=template_id, active=True)
        except Template.DoesNotExist:
            return JsonResponse({'error': '404 Template не найден'}, json_dumps_params={'ensure_ascii': False})
        json_template = {
            'name': template.name,
            'photos': template.photos,
            'posts': template.posts,
            'publics': template.publics,
            'texts': template.texts,
            'times': template.times,
        }
        return JsonResponse({'template': json_template}, json_dumps_params={'ensure_ascii': False})


class IndexView(LoginRequiredMixin, RedirectView):
    pattern_name = 'script:add_post'


@method_decorator(ensure_csrf_cookie, name='dispatch')
class Settings(LoginRequiredMixin, TemplateView):
    template_name = 'script/settings.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['redirect_uri'] = vk_redirect_uri

script/templates/script/add_post.html
{% extends 'script/base.html' %}

{% block title %}Добавить пост{% endblock %}

{% block head %}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/i18n/ru.js"></script>
    {% include 'script/cookie_script_tag.html' %}
    {% include 'script/sweetAlert_script_tag.html' %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'script/post.css' %}">
    <link rel="stylesheet" href="{% static 'script/add_post.css' %}">
    <script src="{% static 'script/add_post.js' %}"></script>
{% endblock %}

{% block header_text %}Добавить пост{% endblock %}

{% block content %}
    <div class="select">
        <label for="template_select">Шаблон</label>
        <select name="template" id="template_select">
            <option value="0">Пустой шаблон</option>
            {% for template in templates %}
                <option value="{{ template.id }}">{{ template.name }}</option>
            {% endfor %}
        </select>
    </div>
    {% include 'script/raw_post.html' with button_text='Добавить' link_label='Ссылки на посты или статьи' public_label='Паблики' text_label='Тексты' image_label='Ссылки на изображения' datetime_label='Время постов' only%}
{% endblock %}

script/templates/script/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Reposter | {% block title %}{% endblock title %}</title>
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0 maximum-scale=1.0">
    {% include 'icons/html_code.html' %}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
          integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP"
          crossorigin="anonymous">
    {% include 'script/jquery_script_tag.html' %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'script/base.css' %}">
    <script src="{% static 'script/sidebar.js' %}"></script>
    {% block head %}

    {% endblock head %}
</head>
<body>
<div>
    <nav>
        <div class="header-wrapper popup-header-wrapper">
            <h1 class="header">Меню</h1>
            <button id="popup-close-button-wrapper">
                <i class="fas fa-times"></i>
            </button>
        </div>
        <div class="links">
            <a href="{% url 'script:list_templates' %}">Шаблоны</a>
            <a href="{% url 'script:add_post' %}">Добавить пост</a>
            <a href="{% url 'script:settings' %}">Настройки</a>
            <a href="{% url 'usermanage:change_password' %}">Сменить пароль</a>
            <a href="{% url 'usermanage:logout' %}">Выход</a>
        </div>
    </nav>
</div>
<div class="content">
    <div class="header-wrapper">
        <button id="menu">
            <i class="fas fa-bars"></i>
        </button>
        {% block header %}
            <h1 class="header">
                {% block header_text %}
                {% endblock header_text %}
            </h1>
        {% endblock header %}
    </div>
    {% block content %}

    {% endblock content %}
</div>
</body>
</html>

script/templates/script/cookie_script_tag.html
<script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>

script/templates/script/jquery_script_tag.html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

script/templates/script/raw_post.html
<form>
    <input type="hidden" name="post_id" value="{{ id }}">
    <div class="container">
        <label for="link_area">{{ link_label }}</label>
        <textarea wrap="soft" name="links" id="link_area" cols="10" rows="5">{{ link }}</textarea>
    </div>
    <div class="container">
        <label for="public_area">{{ public_label }}</label>
        <textarea wrap="soft" name="publics" id="public_area" cols="10" rows="5">{{ public }}</textarea>
    </div>
    <div class="container">
        <label for="text_area">{{ text_label }}</label>
        <textarea wrap="soft" name="texts" id="text_area" cols="30" rows="10">{{ text }}</textarea>
    </div>
    <div class="container">
        <label for="img_area">{{ image_label }}</label>
        <textarea wrap="soft" name="imgs" id="img_area" cols="10" rows="5">{{ image }}</textarea>
    </div>
    <div class="container">
        <label for="datetime_area">{{ datetime_label }}</label>
        {% load tz %}
        <textarea wrap="soft" name="datetimes" id="datetime_area" cols="10" rows="5"
        >{{ datetime|localtime|date:"d.m.Y H:i" }}</textarea>
    </div>
    <div class="container">
        <button class="submit">{{ button_text }}</button>
    </div>
</form>

script/templates/script/settings.html
{% extends 'script/base.html' %}

{% block title %}Настройки{% endblock %}

{% block head %}
    <script src="https://cdn.jsdelivr.net/npm/clipboard@2/dist/clipboard.min.js"></script>
    {% include 'script/cookie_script_tag.html' %}
    {% include 'script/sweetAlert_script_tag.html' %}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/i18n/ru.js"></script>
    {% load static %}
    <link rel="stylesheet" href="{% static 'script/settings.css' %}">
    <script src="{% static 'script/settings.js' %}"></script>
{% endblock %}

{% block header_text %}
    Настройки
{% endblock %}

{% block content %}
    <div class="wrapper">
        {% if text or error %}
            <div class="error">
                {% if text %}
                    <p>{{ text }}</p>
                {% endif %}
                {% if error %}
                    <div>
                        <p>Возникла ошибка: {{ error }}</p>
                        <p>Попробуй еще раз</p>
                    </div>
                {% endif %}
            </div>
        {% endif %}
        <div>
            <button class="settings-but vk-login">
                <a href="https://oauth.vk.com/authorize?client_id=6444581&redirect_uri={{ redirect_uri }}
&display=page&scope=groups,wall,offline&response_type=code&v=5.74">
                    {% if not tg_secret %}Войти ВК{% else %}Обновить токен ВК{% endif %}
                </a>
            </button>
        </div>
        {% if tg_secret %}
            <div>
                <label for="tg_secret_input">
                    Для подключения или изменения аккаунта для уведомлений,
                    отправь <a href="http://t.me/Repost_script_bot" class="link">боту</a> текст ниже и нажми
                    "Проверить"
                </label>
            </div>
            <div>
                <input id="tg_secret_input" type="text" readonly value="{{ tg_secret }}">
                <button class="settings-but" id="copy" data-clipboard-target="#tg_secret_input">
                    <i title="Скопировать" class="far fa-copy"></i>
                </button>
            </div>
            <div>
                <button class="settings-but" id="check">
                    Проверить
                </button>
            </div>
            <div>
                {% if notify_type_id == 0 %}
                    <p id="notify_type_status">Сейчас я не уведомляю ни о чем</p>
                {% elif notify_type_id == 1 %}
                    <p id="notify_type_status">Сейчас я уведомляю только об успешных репостах</p>
                {% elif notify_type_id == 2 %}
                    <p id="notify_type_status">Сейчас я уведомляю только об ошибках</p>
                {% elif notify_type_id == 3 %}
                    <p id="notify_type_status">Сейчас я уведомляю и об успешных репостах, и об ошибках</p>
                {% endif %}
            </div>
            <label for="notify_mode_select">Изменить тип уведомлений на:</label>
            <div>
                <select name="notify_mode" id="notify_mode_select">
                    <option value="0">Не уведомлять</option>
                    <option value="1">Уведомлять только об успешных репостах</option>
                    <option value="2">Уведомлять только об ошибках</option>
                    <option value="3">Уведомлять обо всем</option>
                </select>
                <button class="settings-but" id="save">
                    Сохранить
                </button>
            </div>
        {% endif %}
    </div>
{% endblock %}

script/templates/script/sweetAlert_script_tag.html
<script defer src="https://unpkg.com/sweetalert2@7.18.0/dist/sweetalert2.all.js"></script>

script/templates/script/template.html
{% extends 'script/base.html' %}

{% block title %}
    {% if form.name.value %}
        Шаблон {{ form.name.value }}
    {% else %}
        Новый шаблон
    {% endif %}
{% endblock %}

{% block head %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'script/template.css' %}">
    {% include 'script/sweetAlert_script_tag.html' %}
    {% include 'script/cookie_script_tag.html' %}
    <script src="{% static 'script/template.js' %}"></script>
{% endblock %}

{% block header_text %}
    {% if template_id %}
        Шаблон <span class="template-name">{{ form.name.value }}</span>
    {% else %}
        Новый шаблон
    {% endif %}
{% endblock %}

{% block content %}
    {% if template_id %}
        <div class="wrapper">
            <div class="actions">
                <a href="{% url 'script:copy_template' template_id=template_id %}">Скопировать</a>
                <span id="delete-but" data-id="{{ template_id }}"
                      data-template-name="{{ form.name.value }}">Удалить</span>
            </div>
        </div>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="field-wrapper">
            {{ form.name.errors }}
            {{ form.name.label_tag }}
            {{ form.name }}
        </div>
        <div class="fancy-fields-wrapper">
            {% for field in form %}
                {% if not forloop.counter0 == 0 %}
                    <div class="field-wrapper">
                        {{ field.errors }}
                        {{ field.label_tag }}
                        <div class="textarea-wrapper">
                            {{ field }}
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
        <div class="button-wrapper">
            <button class="submit">
                Сохранить
            </button>
        </div>
    </form>
{% endblock %}

script/templates/script/template_list.html
{% extends 'script/base.html' %}

{% block title %}Шаблоны{% endblock %}

{% block head %}
    {% include 'script/cookie_script_tag.html' %}
    {% include 'script/sweetAlert_script_tag.html' %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'script/dragula.min.css' %}">
    <link rel="stylesheet" href="{% static 'script/template_list.css' %}">
    <script src="{% static 'script/template_list.js' %}"></script>
{% endblock %}

{% block header %}
    {{ block.super }}
    <a href="{% url 'script:create_template' %}" id="create_template_link" title="Создать новый"
       class="create-new"><span class="plus-text">+</span></a>
{% endblock %}

{% block header_text %}
    Шаблоны
{% endblock %}

{% block content %}
    <ul id="template_list">
        {% for object in object_list %}
            <li data-id="{{ object.id }}">
                <div>
                    <span class="drag-handle"><i class="fas fa-grip-lines"></i></span>
                    <a href="{% url 'script:template_detail' template_id=object.id %}"
                       class="template__name"
                    >{{ object.name }}</a>
                </div>
                <div class="actions">
                    <a href="{% url 'script:copy_template' template_id=object.id %}" class="copy-but">
                        <i title="Скопировать" class="far fa-copy"></i>
                    </a>
                    <span class="delete-but">
                        <i title="Удалить" class="far fa-trash-alt"></i>
                    </span>
                </div>
            </li>
        {% empty %}
            <li>Еще нет шаблонов, создай первый сейчас!</li>
        {% endfor %}
    </ul>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/dragula/3.7.2/dragula.min.js'></script>
{% endblock %}

script/templates/script/update_post.html
{% extends 'script/base.html' %}

{% block title %}Пост {{ id }}{% endblock %}

{% block header_text %}Пост {{ id }}{% endblock %}

{% block head %}
    {% include 'script/sweetAlert_script_tag.html' %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'script/post.css' %}">
    {% include 'script/jquery_script_tag.html' %}
    {% include 'script/cookie_script_tag.html' %}
    <script src="{% static 'script/update_post.js' %}"></script>
{% endblock %}

{% block content %}
    {% include 'script/raw_post.html' with button_text='Обновить и запустить' link_label='Ссылка на пост' public_label='Паблик' text_label='Текст' image_label='Ссылка на изображение' datetime_label='Время поста' %}
{% endblock %}

script/templates/script/working_post.html
{% extends 'script/base.html' %}

{% block title %}Пост в работе{% endblock %}

{% block header_text %}Лучше не менять сейчас этот пост{% endblock %}

{% block content %}
    <h3>Потому что я его сейчас прокликиваю</h3>
    <h3>Зайди сюда через пару минут</h3>
{% endblock %}